# Generated by Django 4.1.2 on 2022-11-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Add_news',
        ),
    ]
